### ISSUE TITLE
Could you guys please update this awesome source to working with Terraform version 0.14?

### ISSUE THREAD

**Issue by duanvnc** [mineiros-io/terraform-aws-cognito-user-pool#26]
I just upgraded the Terraform version into 0.14 and it couldn't work with this source code anymore.

So, can you please resolve that issue?

**Comment by mariux** [comment]
Yes, of course will set up our testing environment to cover tf 0.14 and update the versioning constraints, thanks for reporting.

**Comment by mariux** [comment]
@duanvnc I just released v0.4.0 with support for Terraform 0.14.x. Please test and report back or open a new issue if you face any problems... happy coding.. ;)
