### ISSUE TITLE
Support Account recovery settings

### ISSUE THREAD

**Issue by wesnick** [mineiros-io/terraform-aws-cognito-user-pool#32]
A recent update to AWS provider added a cognito setting:
https://github.com/hashicorp/terraform-provider-aws/pull/12444

As a consequence, mineiros cognito module is no longer idempotent

```
      - account_recovery_setting {
        }
```

**Comment by mariux** [comment]
hi @wesnick,

thank you for taking the time reporting this issue.

As we did not add support for `account_recovery_setting` yet, this is likely an issue of the provider itself: I found the upstream bug report here: https://github.com/hashicorp/terraform-provider-aws/issues/17228 

Please upvote the upstream bug (I just did so) so it gets fixed, where it is broken.

Fixing it here would require us to drop support for 2.x provider, which we might do soon anyway.

**Comment by wesnick** [comment]
Thanks, I have upvoted upstream.
