### ISSUE TITLE
email_message_by_link strange readme

### ISSUE THREAD

**Issue by gpkc** [mineiros-io/terraform-aws-cognito-user-pool#46]
According to the readme:

> email_message_by_link: (Optional string)
> 
> The email message template for sending a confirmation link to the user, it must contain the {##Click Here##} placeholder. Default is "Please click the link below to verify your email address. {##Verify Email##}.".

How come `{##Click Here##}` is mandatory yet the default doesn't contain it?

**Comment by soerenmartius** [comment]
Hi @gpkc, 

thanks for reporting this. We implemented this module according to the information given in the [documentation of the provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool).

Imho, the placeholder is required since otherwise, Cognito will not be able to generate and insert the confirmation link?

**Comment by gpkc** [comment]
@soerenmartius Yes there should be a placeholder but the explanation text states:
> The email message template for sending a confirmation link to the user, it must contain the `{##Click Here##}` placeholder.

However, the default value contains `{##Verify Email##}` and not `{##Click Here##}`

**Comment by soerenmartius** [comment]
> @soerenmartius Yes there should be a placeholder but the explanation text states:
> 
> > The email message template for sending a confirmation link to the user, it must contain the `{##Click Here##}` placeholder.
> 
> However, the default value contains `{##Verify Email##}` and not `{##Click Here##}`

@gpkc it seems that this has changed. Older version of the provider required it to be`{##Verify Email##}` as you can see [here](https://github.com/hashicorp/terraform-provider-aws/blame/51e9e2a837782e2278b52197dc28a3303accfee7/website/docs/r/cognito_user_pool.markdown#L118).

We will review the provider requirements, might adust the min required version, and update the docs in a little while.

**Comment by mariux** [comment]
Afaik: it is required to have `{##Any Text##}` placeholder where `Any Text` will be the link text... so `{##Click here##}` should do as well as `{##Verify Email##}` as would `{##Follow this link##}`. 

So whatever the tag shows should work in the context of the rest of the message - Which it does in the default?

The documentation is really bad in AWS for this. 

I hope this helps.

**Comment by gpkc** [comment]
Oh I see, that makes sense then. Yes the documentation seems to be very bad in that sense, as it's not mentioned anywhere that I could find that the text content is arbitrary. Thanks!
Might be that this can be closed then

**Comment by soerenmartius** [comment]
I am gonna add this to the docs to avoid future confusion!

**Comment by soerenmartius** [comment]
Closed in favor of #48
