### ISSUE TITLE
Support declaring resource servers for a user pool

### ISSUE THREAD

**Issue by cornwe19** [mineiros-io/terraform-aws-cognito-user-pool#54]
Some app clients require assigning custom scopes to client users which are based on resource servers declared on the user pool.

I'd like to be able to dynamically declare resource servers and scopes via this module per the [AWS Cognito Resource Server terraform documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_resource_server).

The syntax I'm envisioning for configuring resource servers might look something like the following:

```hcl
resource_servers = [
    {
      identifier = "https://api.resourceserver.com"
      name       = "API"
      scopes     = [
        {
          scope_name = "users:read"
          scope_description = "Read user data"
        },
        {
          scope_name = "users:write"
          scope_description = "Write user data"
        }
      ]
    }
  ]
```

**Comment by soerenmartius** [comment]
This has been added in https://github.com/mineiros-io/terraform-aws-cognito-user-pool/releases/tag/v0.9.1

Thanks again @cornwe19 for providing this feature!

**Comment by cornwe19** [comment]
Excellent! Happy to help. Thanks!
