### ISSUE TITLE
aws provider 4.0

### ISSUE THREAD

**Issue by cemo** [mineiros-io/terraform-aws-cognito-user-pool#64]
It seems that current aws provider is constrained as `aws = ">= 3.50, < 4.0"`.  AWS Provider 4.0.0 has released today. Would you please a cut compatible release please?

**Comment by soerenmartius** [comment]
Hi @cemo, thanks for being patient with us! We just released [v0.9.2](https://github.com/mineiros-io/terraform-aws-cognito-user-pool/releases/tag/v0.9.2) which comes with support for the AWS provider `v4`

Again, thanks bringing this to our attention!
